name: Xbox build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: |
            base-devel
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gcc

      - name: Configure CMake with MinGW
        shell: msys2 {0}
        run: |
          cd "$(cygpath -u "$GITHUB_WORKSPACE")"
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_USER_BUILD=ON -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..

      - name: Build
        shell: msys2 {0}
        run: |
          cd "$(cygpath -u "$GITHUB_WORKSPACE")/build"
          mingw32-make

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ChonkyStation3 
          path: build/Release/libChonkyStation3.dll

  build_xbox:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: |
            base-devel
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gcc
            python3

      - name: Configure and Build Xbox Target with MinGW
        shell: msys2 {0}
        run: |
          cd "$(cygpath -u "$GITHUB_WORKSPACE")"
          pacman -Syu --noconfirm
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          mkdir -p buildxbox
          cd buildxbox
          cmake -G "MinGW Makefiles" -DENABLE_XBOX_BUILD=ON ..
          mingw32-make
          if [ -f "libChonkyStation3" ]; then
              mv libChonkyStation3 libChonkyStation3.dll
          fi

      - name: Upload Xbox Executable
        uses: actions/upload-artifact@v4
        with:
          name: ChonkyStation3_xbox
          path: buildxbox/libChonkyStation3.dll
